### ISSUE TITLE
InvalidProjectFileException with OmniSharp

### ISSUE THREAD

**Issue by NoTuxNoBux** [wackoisgod/com.unity.ide.vscode#1]
I'm hitting the following error when loading a Unity project with the SDK support branch:

```
Starting OmniSharp server at 20/7/2022 15:13:11
    Target: /home/user/testproject/testproject.sln

OmniSharp server started with .NET 6.0.106
.
    Path: /home/werk/.vscode-oss/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/.omnisharp/1.39.0-net6.0/OmniSharp.dll
    PID: 41017

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to /usr/share/dotnet/dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.106 17.0.0 - "/usr/share/dotnet/sdk/6.0.106/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.106 17.0.0 - "/usr/share/dotnet/sdk/6.0.106/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/user/testproject/testproject.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/user/testproject/Scripts.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/user/testproject/Tests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/user/testproject'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/user/testproject' on host 30161.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/user/testproject/Scripts.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        Items that are outside Target elements must have one of the following operations: Include, Update, or Remove.
[fail]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/user/testproject/Scripts.csproj'.
Microsoft.Build.Exceptions.InvalidProjectFileException: Items that are outside Target elements must have one of the following operations: Include, Update, or Remove.  /home/user/testproject/Scripts.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1,T2](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Construction.ProjectParser.ParseProjectItemElement(XmlElementWithLocation element, ProjectItemGroupElement parent)
   at Microsoft.Build.Construction.ProjectParser.ParseProjectItemGroupElement(XmlElementWithLocation element, ProjectElementContainer parent)
   at Microsoft.Build.Construction.ProjectParser.Parse()
   at Microsoft.Build.Construction.ProjectParser.Parse(XmlDocumentWithLocation document, ProjectRootElement projectRootElement)
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCacheBase projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, ProjectRootElementCacheBase projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.<>c.<OpenProjectOrSolution>b__208_0(String path, ProjectRootElementCacheBase cache)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.OpenProjectOrSolution(String fullPath, IDictionary`2 globalProperties, String toolsVersion, ProjectRootElementCacheBase projectRootElementCache, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Project.ProjectImpl..ctor(Project owner, String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath, IReadOnlyDictionary`2 projectConfigurationsInSolution, IList`1 loggers) in /Users/runner/work/1/s/src/OmniSharp.MSBuild/ProjectLoader.cs:line 162
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath, IReadOnlyDictionary`2 configurationsInSolution) in /Users/runner/work/1/s/src/OmniSharp.MSBuild/ProjectLoader.cs:line 84
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader, Guid sessionId, DotNetInfo dotNetInfo) in /Users/runner/work/1/s/src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs:line 117
   at OmniSharp.MSBuild.ProjectManager.<>c__DisplayClass32_0.<LoadProject>b__0() in /Users/runner/work/1/s/src/OmniSharp.MSBuild/ProjectManager.cs:line 305
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in /Users/runner/work/1/s/src/OmniSharp.MSBuild/ProjectManager.cs:line 316
/home/user/testproject/Scripts.csproj(0,0)
```

The error message is clear, but it's not pointing to any specific lines, so I don't immediately know what elements are causing this problem.

**Comment by NoTuxNoBux** [comment]
I also only get rudimentary autocompletion where OmniSharp recognizes .NET classes, but I can't use code navigation for my own classes until I manually open them first. The indexed document count is around 37, which is way too low, but this could all just be due to the above issue, so I'll report a separate issue if this still happens after the above problem is resolved.

**Comment by wackoisgod** [comment]
@NoTuxNoBux anyway I could get you to upload the csproj file just so I can see what its outputting or the unity project itself so I can test against what you are doing. 

Also what version of Unity are you using?

**Comment by NoTuxNoBux** [comment]
I'll try to reproduce the issue in a smaller test project, as the project is proprietary. I can already say that

* The Unity version is 2021.3.6.
* It doesn't reproduce with a new project created from the 3D template.
* The affected project uses separate assembly definitions.
* The affected project uses [the MRTK](https://github.com/microsoft/MixedRealityToolkit-Unity).
* The affected project uses some NuGetForUnity packages.

I'm guessing that the problem is going to be in one of those areas, but I will try to find out more.

**Comment by NoTuxNoBux** [comment]
I found the problem. `CodeAnalysisRuleSet` is put in the same `ItemGroup` the `Analyzer` elements are in. It's supposed to be in a `PropertyGroup` parent element, which was also the case in Unity's original package.

After moving it temporarily, my projects both seem to work correctly and the rudimentary autocompletion problem seems to be solved. Code analyzers also work correctly using the ruleset. :slightly_smiling_face:

**Comment by wackoisgod** [comment]
So this should be resolved now in the latest changelist
